rri visualize scripts improvements

diff --git a/scripts/rri-visualize b/scripts/rri-visualize
--- a/scripts/rri-visualize
+++ b/scripts/rri-visualize
@@ -39,83 +39,89 @@ usage_fct(){
 
 if [ -f "rri.R" ]
 then
-rscript=rri.R
+  rscript=rri.R
 elif [[ ! -f "$rscript" ]]
 then
-if [[ -f "${RRI_PATH}/rri.R" ]]
-then
-rscript=${RRI_PATH}/rri.R
-else
-echo "The required R script rri.R has not been found. Set the environment variable RRI_PATH to the directory that contains it. Leaving..."
-exit 1
-fi
+  if [[ -f "${RRI_PATH}/rri.R" ]]
+  then
+    rscript=${RRI_PATH}/rri.R
+  else
+    echo "The required R script rri.R has not been found. Set the environment variable RRI_PATH to the directory that contains it. Leaving..."
+    exit 1
+  fi
 fi
 #No arguments
 if [ $# -eq 0 ]
 then
-usage_fct
+  usage_fct
 fi
 #Test arguments
 while [ $# -gt 1 ]
 do
-if [ $1 = "-h" ] || [ $1 = "--help" ]
-then
-usage_fct
-exit 0
-elif [ $1 = "-c" ] || [ $1 = "--clean" ]
-then
-clean="true"
-elif [ $1 = "-s" ] || [ $1 = "--size" ]
-then
-shift
-width=$1
-shift
-height=$1
-elif [ $1 = "-d" ] || [ $1 = "--dpi" ]
-then
-shift
-dpi=$1
-elif [ $1 = "-t" ] || [ $1 = "--threads" ]
-then
-shift
-threads=$1
-echo "Using $threads threads"
-fi
-shift
+  if [ $1 = "-h" ] || [ $1 = "--help" ]
+  then
+    usage_fct
+    exit 0
+  elif [ $1 = "-c" ] || [ $1 = "--clean" ]
+  then
+    clean="true"
+  elif [ $1 = "-s" ] || [ $1 = "--size" ]
+  then
+    shift
+    width=$1
+    shift
+    height=$1
+  elif [ $1 = "-d" ] || [ $1 = "--dpi" ]
+  then
+    shift
+    dpi=$1
+  elif [ $1 = "-t" ] || [ $1 = "--threads" ]
+  then
+    shift
+    threads=$1
+    echo "Using $threads threads"
+  fi
+  shift
 done
 if [ ! -d $1 ]
 then
-echo "$1 is not a valid directory"
-usage_fct
-exit 1
+  echo "$1 is not a valid directory"
+  usage_fct
+  exit 1
 fi
 input_dir=$1
 if [ $clean = "true" ]
 then
-for sub_dir in $input_dir/*
-do
-if [ -d $sub_dir ]
-then
-echo "Cleaning $sub_dir directory"
-rm -f $sub_dir/*.pdf $sub_dir/.*.pdf
-fi
-done
+  for sub_dir in $input_dir/*
+  do
+    if [ -d $sub_dir ]
+    then
+      if [[ $string != *"rri.profiling" ]]
+      then
+        echo "Cleaning $sub_dir directory"
+        rm -f $sub_dir/*.pdf $sub_dir/.*.pdf
+      fi
+    fi
+  done
 else
-it=0
-for sub_dir in $input_dir/*
-do
-if [ -d $sub_dir ]
-then
-echo "Processing $sub_dir directory"
-instance=`basename $sub_dir`
-R --slave --vanilla --args $input_dir $sub_dir $instance $sub_dir $width $height $dpi < $rscript &
-it=$((it + 1))
-if [ $it -eq $threads ]
-then
-it=0
-wait
-fi
-fi
-done
-wait
+  it=0
+  for sub_dir in $input_dir/*
+  do
+    if [ -d $sub_dir ]
+    then
+      if [[ $string != *"rri.profiling" ]]
+      then
+        echo "Processing $sub_dir directory"
+        instance=`basename $sub_dir`
+        R --slave --vanilla --args $input_dir $sub_dir $instance $sub_dir $width $height $dpi < $rscript &
+        it=$((it + 1))
+        if [ $it -eq $threads ]
+        then
+          it=0
+          wait
+        fi
+      fi
+    fi
+  done
+  wait
 fi
